name: taek_it_easy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  step_progress_indicator: ^1.0.2
  youtube_player_flutter: ^8.1.2
  flutter_calendar_carousel: ^2.4.2
  table_calendar: ^3.0.9
  fl_chart: ^0.66.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.2.0
  device_info_plus: ^9.1.2
  
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.10.0
  path_provider: ^2.1.2
  google_mlkit_commons: ^0.6.1
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
